FROM node:18-alpine

WORKDIR /usr/src/app

# Install production dependencies (project has frontend & backend deps in root package.json)
COPY package.json package-lock.json* ./
RUN npm install --production

# Copy project
COPY . .

ENV NODE_ENV=production
ENV PG_HOST=db

EXPOSE 3000

CMD ["node", "backend/server.js"]
